### ISSUE TITLE
Incorrect gitignore file leads to untracked content

### ISSUE THREAD

**Issue by mahoneyrAC** [gkapfham/gatorgrader#1]
I'm using the gator grader system and came across a bug that resulted in untracked content. Here are the derived files that should not be tracked by the system: 

```
	__pycache__/
	bin/
	lib/
	lib64
	pip-selfcheck.json
	pyvenv.cfg
	share/
```
Please update the `.gitignore` to avoid these files and directories from being tracked.

**Comment by toccinAC** [comment]
This has been happening to me as well, when the command git status is done in the gator grader repository.

**Comment by gkapfham** [comment]
Hello @mahoneyrAC and @toccinAC! Thanks for pointing out that this repository did not have a `.gitignore` file and thus certain derived files would be flagged as needed to be committed to the repository. I have added the requested file and thus I am closing this issue. If you notice any further problems, then please report back on this issue.
