### ISSUE TITLE
Sentence Counting Does not Work if there Are No Sentences in Paragraph

### ISSUE THREAD

**Issue by gkapfham** [gkapfham/gatorgrader#12]
The current version of GatorGrader does not work if it checks an input file for the number of sentences in a paragraph and there are no sentences. For instance, this could happen for the following type of Markdown:

```
# Header

```

Note that there is a header and then no paragraph below the header. This will currently cause GatorGrader to crash for its current invocation. In the short term, the best workaround is to always give students template markdown files that contains something like:

```
# Header

Type your answer here.
```

But, @Michionlion, @jjumadinova, and @toccinAC. I have a fix in mind for this issue and will create a branch and a pull request for it either late this week or at the start next week.

**Comment by Michionlion** [comment]
This is solved (and changed) in PR #24.
