### ISSUE TITLE
Define a Requirements File Format

### ISSUE THREAD

**Issue by Michionlion** [gkapfham/gatorgrader#15]
We should define a format for a file that assignment requirements should be made in - then the actual checking can be separated from the command-line arguments to gatorgrader, and @toccinAC's python program could parse a file in this format and then call `gatorgrader.py` with the necessary arguments.

**Comment by gkapfham** [comment]
Yes, I agree that this is a good idea, @Michionlion. Can you start to work with @toccinAC to think about what this format should look like? If you can record your ideas here on the issue track, it would be greatly appreciated.

**Comment by Michionlion** [comment]
This issue has been closed since the [GatorGradle](https://github.com/gatored/gatorgradle) repository will handle distribution and assignment creation tasks such as this.
