### ISSUE TITLE
Issue when doing a check on reflections

### ISSUE THREAD

**Issue by toccinAC** [gkapfham/gatorgrader#2]
Ben Watto came in with an issue that is being brought up when he does the ./gatorgrader.sh --check command. If there is a paragraph in the reflection.md document that is over one line it throws an error that is writing/reflection.md:3: MD013 Line Length. There are no errors in the paragraph, but the system continues to throw the error.

**Comment by gkapfham** [comment]
Hello @toccinAC! First, thanks for raising this issue about GatorGrader. I would suggest that you not mention the names of specific students in this issue tracker as the idea is to use it to resolve specific issues about the GatorGrader tool. Does this sound reasonable?

Finally, I think that the error that you are seeing is expected. GatorGrader uses the `mdl` program to check all of the markdown code. You can see these commands being run in the `gatorgrader.sh` file, which is technically not in this repository but rather provided in a starter repository.

What is happening is that a user of GatorGrader is writing all of their text in a single line and not including any line wraps. This is being flagged as incorrect by `mdl`. If the student has their paragraph open in `gvim`, then they can type `gqip` in command-mode and it will reformat the text.

Let me know if this does not work correctly!
