### ISSUE TITLE
Couldn't Effectively Count Sentences with the Phrase "A through L." in a Paragraph.

### ISSUE THREAD

**Issue by durcij** [gkapfham/gatorgrader#20]
I was running into an issue with the sentence counting feature in a written reflection.  After numerous attempts to try to troubleshoot it, the error seemed to stem from the use of the phrase, "A through L."

**Comment by Michionlion** [comment]
Hi @durcij! Thanks for reporting this bug! Can you provide the text that is not getting counted correctly?

**Comment by Michionlion** [comment]
I've added two test cases with the below paragraphs for `gatorgrader_fragments.py:count_sentences()` on [this branch](/gkapfham/gatorgrader/tree/i-20-sentence-count-bug):

This test case passes:
```
This is a paragraph with A through L in it. It should pass.
It should also have three sentences
```

This test case fails:
```
This is a sentence ending in A through L. It should also pass.
The paragraph should have three sentences
```

I will investigate further, but this seems to be a bug with `nltk`. Excellent work finding this, @durcij!

**Comment by Michionlion** [comment]
I've confirmed that the bug is present in `nltk` itself. It can be replicated by running this code:
```
import nltk
paragraph = 'A sentence of one small part. This second one ends '
                    'with A through L. And here is a third sentence.'
result = nltk.sent_tokenize(paragraph)
print(result)
```
Result will then print as `['A sentence of one small part.', 'This second one ends with A through L. And here is a third sentence.']`. Another thing to note is that a sentence must not be the last sentence in the paragraph, since then the tokenization simply ends, and it seems as though it works.

**Comment by Michionlion** [comment]
After more investigation, this seems to happen whenever there is one of the below characters followed by a period (`.`):
```
c
d
e
f
g
h
k
l
m
n
p
r
s
t
v
w
C
D
E
F
G
H
K
L
M
N
P
R
S
T
V
W
```

**Comment by Michionlion** [comment]
For future use, I think that we will not be able to fix this bug ourselves. Instead, students should avoid typing the characters seen above as the last word in a sentence. As a sanity check, we could perhaps check if more than `x` periods were observed when checking for `x` sentences, and if so, and the check failed, give a warning message to students about this problem.

**Comment by Michionlion** [comment]
For future reference, a possible workaround or patch would be to see if the paragraph currently being tested contains one of the strings that causes this problem, and if so, increase the count by one, unless it ends with that string.

**Comment by yeeunmariakim** [comment]
We have agreed on changing to a word count requirement instead of the sentence count as to remove our dependency on the NLTK library.

**Comment by Michionlion** [comment]
PR #24 implements the agreed upon word count check to replace the sentence count check. This bug, since it is from `nltk`, now does not affect GatorGrader.
