### ISSUE TITLE
Creating a python file so that the bash script is not needed

### ISSUE THREAD

**Issue by toccinAC** [gkapfham/gatorgrader#22]
I am going to make a python file that contains the actions that are completed in the gatorgrader.sh so that the system is easier to configure. This will also give gatorgrader the ability to be used with different programming languages.

**Comment by Michionlion** [comment]
@toccinAC Can we work together to integrate this with [gatorgrader-plugin](https://github.com/Michionlion/gatorgrader-plugin)

**Comment by Michionlion** [comment]
Closing this issue per past meetings. Look for [GatorGradle](https://github.com/gatored/gatorgradle) to get this functionality.
