### ISSUE TITLE
Check the Number of Sentences in a Written Paragraph

### ISSUE THREAD

**Issue by gkapfham** [gkapfham/gatorgrader#6]
Currently GatorGrader can check to see how many paragraphs are in a written
document. However, it does not enforce how many sentences are inside of the
paragraph. As such, it is possible for a student to write a very short
paragraph and still fulfill the GatorGrader checks. So, GatorGrader should
check the number of sentences in a written paragraph and then pass or fail a
test case based on the number that is found.

**Comment by gkapfham** [comment]
Hi @Michionlion and @jjumadinova and @toccinAC! There is a version of this feature that is almost working. However, if you check Issue #12 you will see that this feature is not yet correctly implemented. So, you can ask GatorGrader to check for the number of sentences in a paragraph, but only if you do not specify "empty paragraphs". For your reference, here is an example of how to try out this command:

```
python3 gatorgrader/gatorgrader.py --nowelcome --directories writing --checkfiles reflection.md --paragraphs 3 --sentences 3
```

Please let me know if you find that there are other ways in which the current version of this feature is not working correctly.

**Comment by Michionlion** [comment]
This is deprecated in favor of the `--wordcount` option currently on PR #24, and documented in `README.md` on that branch.
