### ISSUE TITLE
Report Useful Summary Diagnostics

### ISSUE THREAD

**Issue by gkapfham** [gkapfham/gatorgrader#8]
Currently, if a build does not pass correctly, then the GatorGrader program will
say that the build fails. However, a student then has to scroll all of the way
through the output in order to see what is broken. It would be useful if
GatorGrader had a way to store state and then to display a useful summary
diagnostic after running all of the checks. Right now, I don't think that this
is possible because GatorGrader is repeatedly run in a "one shot" fashion and it
is only the Bash script that calls GatorGrader. This script program does not
maintain any state and thus this feature may be difficult to implement unless
GatorGrader ships with a Python program that calls GatorGrader.

**Comment by Michionlion** [comment]
[GatorGradle](https://github.com/gatored/gatorgradle), the program described in this issue, is now available and being worked on. Therefore any further discussion should take place in its repository (and would be welcomed).
